spring:
  datasource:
    # Configurazione delle proprietà del datasource per il database MySQL
    url: jdbc:mysql://localhost:3306/spring_social?useSSL=false&allowPublicKeyRetrieval=true
    username: tuo_username
    password: tua_password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            # Configurazione delle credenziali OAuth2 per l'autenticazione tramite Google
            clientId: <client_id>
            clientSecret: <client_secret>
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            # Configurazione delle credenziali OAuth2 per l'autenticazione tramite Facebook
            clientId: <client_id>
            clientSecret: <client_secret>
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            # Configurazione delle credenziali OAuth2 per l'autenticazione tramite GitHub
            clientId: <client_id>
            clientSecret: <client_secret>
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            # Configurazione delle URL per l'autenticazione tramite Facebook
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v18.0/me?fields=id,first_name,middle_name,last_name,name,email,verified&transport=cors
app:
  auth:
    # Configurazione delle proprietà dell'autenticazione, inclusa la segretezza del token e la sua durata
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000

  cors:
    # Configurazione delle origini consentite per le richieste CORS
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # Configurazione delle URI autorizzate per il redirect dopo l'autenticazione OAuth2
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

